# Generated by Django 3.2.9 on 2021-11-10 13:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_title', models.CharField(max_length=50)),
                ('res_author', models.CharField(max_length=50)),
                ('res_copies', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowed_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_borrowing_date', models.DateTimeField(auto_now_add=True)),
                ('recorded_returning_date', models.DateTimeField(default=datetime.datetime(2021, 12, 10, 13, 50, 12, 611864))),
                ('borrowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceApp.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
