# Generated by Django 4.0.4 on 2022-05-08 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceApp', '0008_alter_borrowed_resource_recorded_returning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed_resource',
            name='recorded_returning_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 11, 38, 41, 8213)),
        ),
    ]
